import { NextRequest, NextResponse } from 'next/server'
import { cookies } from 'next/headers'
import { createRouteHandlerClient } from '@/lib/supabase'
import type { TicketCategory, TicketPriority } from '@/types/database'

// GET /api/v1/tickets - List all tickets for the agency
export async function GET(request: NextRequest) {
  try {
    const supabase = await createRouteHandlerClient(cookies)

    const {
      data: { session },
      error: sessionError,
    } = await supabase.auth.getSession()

    if (sessionError || !session) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      )
    }

    // Get query params for filtering
    const { searchParams } = new URL(request.url)
    const status = searchParams.get('status')
    const priority = searchParams.get('priority')
    const clientId = searchParams.get('client_id')
    const assigneeId = searchParams.get('assignee_id')
    const category = searchParams.get('category')
    const search = searchParams.get('search')

    // Build query - RLS will filter by agency_id
    let query = supabase
      .from('ticket')
      .select(`
        *,
        client:client_id (
          id,
          name,
          health_status
        ),
        assignee:assignee_id (
          id,
          first_name,
          last_name,
          avatar_url
        )
      `)
      .order('created_at', { ascending: false })

    // Apply filters
    if (status) {
      query = query.eq('status', status)
    }
    if (priority) {
      query = query.eq('priority', priority)
    }
    if (clientId) {
      query = query.eq('client_id', clientId)
    }
    if (assigneeId) {
      query = query.eq('assignee_id', assigneeId)
    }
    if (category) {
      query = query.eq('category', category)
    }
    if (search) {
      query = query.or(`title.ilike.%${search}%,description.ilike.%${search}%`)
    }

    const { data: tickets, error } = await query

    if (error) {
      console.error('Error fetching tickets:', error)
      return NextResponse.json(
        { error: 'Failed to fetch tickets' },
        { status: 500 }
      )
    }

    return NextResponse.json({ data: tickets })
  } catch (error) {
    console.error('Tickets GET error:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}

// POST /api/v1/tickets - Create a new ticket
export async function POST(request: NextRequest) {
  try {
    const supabase = await createRouteHandlerClient(cookies)

    const {
      data: { session },
      error: sessionError,
    } = await supabase.auth.getSession()

    if (sessionError || !session) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      )
    }

    const body = await request.json()
    const { client_id, title, description, category, priority, assignee_id, due_date } = body as {
      client_id: string
      title: string
      description: string
      category: TicketCategory
      priority: TicketPriority
      assignee_id?: string | null
      due_date?: string | null
    }

    // Validate required fields
    if (!client_id || !title || !description || !category || !priority) {
      return NextResponse.json(
        { error: 'Missing required fields: client_id, title, description, category, priority' },
        { status: 400 }
      )
    }

    // Get agency_id from user's JWT claims or profile
    const { data: profile } = await supabase
      .from('user')
      .select('agency_id')
      .eq('id', session.user.id)
      .single()

    if (!profile?.agency_id) {
      return NextResponse.json(
        { error: 'Agency not found for user' },
        { status: 400 }
      )
    }

    // Create ticket - number will be auto-generated by trigger
    const { data: ticket, error } = await supabase
      .from('ticket')
      .insert({
        agency_id: profile.agency_id,
        client_id,
        title,
        description,
        category,
        priority,
        assignee_id: assignee_id || null,
        due_date: due_date || null,
        created_by: session.user.id,
      })
      .select(`
        *,
        client:client_id (
          id,
          name,
          health_status
        ),
        assignee:assignee_id (
          id,
          first_name,
          last_name,
          avatar_url
        )
      `)
      .single()

    if (error) {
      console.error('Error creating ticket:', error)
      return NextResponse.json(
        { error: 'Failed to create ticket' },
        { status: 500 }
      )
    }

    return NextResponse.json({ data: ticket }, { status: 201 })
  } catch (error) {
    console.error('Tickets POST error:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}
